version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
    - 80:80
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      # wpdb: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
    volumes:
    - ./_site/wp-content:/var/www/html/wp-content
    # - wordpress:/var/www/html
    # - ./wp-content:/var/www/html # THIS?

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
    - ./mysql/:/docker-entrypoint-initdb.d
    # - ./db:/var/lib/mysql/

# volumes:
#   wordpress:
#   db: